// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGbZfmPz5rbuhGXFK5d65EwPj_ovK3MWA',
    appId: '1:28155988173:web:6fc61e41070c5fdff2c184',
    messagingSenderId: '28155988173',
    projectId: 'dementiavirtualmemory',
    authDomain: 'dementiavirtualmemory.firebaseapp.com',
    storageBucket: 'dementiavirtualmemory.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCquQQsf9jiR-T41JJIDeahd41R_eWXbRw',
    appId: '1:28155988173:android:004a6c04b5538405f2c184',
    messagingSenderId: '28155988173',
    projectId: 'dementiavirtualmemory',
    storageBucket: 'dementiavirtualmemory.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHaUDoGR0z0jQ4xiA4ibsBRqMWp1BzSvg',
    appId: '1:28155988173:ios:8c2a56dcf9083bd5f2c184',
    messagingSenderId: '28155988173',
    projectId: 'dementiavirtualmemory',
    storageBucket: 'dementiavirtualmemory.appspot.com',
    iosBundleId: 'com.example.dementiaVirtualMemory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHaUDoGR0z0jQ4xiA4ibsBRqMWp1BzSvg',
    appId: '1:28155988173:ios:8c2a56dcf9083bd5f2c184',
    messagingSenderId: '28155988173',
    projectId: 'dementiavirtualmemory',
    storageBucket: 'dementiavirtualmemory.appspot.com',
    iosBundleId: 'com.example.dementiaVirtualMemory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGbZfmPz5rbuhGXFK5d65EwPj_ovK3MWA',
    appId: '1:28155988173:web:68fe71ec5ab6e094f2c184',
    messagingSenderId: '28155988173',
    projectId: 'dementiavirtualmemory',
    authDomain: 'dementiavirtualmemory.firebaseapp.com',
    storageBucket: 'dementiavirtualmemory.appspot.com',
  );
}
